# 基本配置
Env = "local" # 环境: pre 测试 beta 预发 release 生产
Mode="debug" #release debug test gin.mode
APPURL = ""
AppName = "go-demo"

# 端口
Port=3003

# pprof端口
PprofPort=9003

RpcPort=30030

# log
[log]
    #debug info warn error
    LogLevel = "debug"
    LogFileStdout = "./go-demo.log"
    LogFileErrorStdout = "./go-demo.error.log"
    AppKey = "go-demo"

# mysql 配置
[mysqlMaster]
    Host="127.0.0.1:3306"
	Password = "123456"
	User = "root"
	Database = "go-demo"
	MaxLifetime = 5
	MaxIdleConns = 10

[mysqlSlave]
    Host="127.0.0.1:3306"
	Password = "123456"
	User = "root"
	Database = "go-demo"
	MaxLifetime = 5
	MaxIdleConns = 10

[pgsqlMaster]
    Host="127.0.0.1:5432"
	Password = "123456"
	User = "root"
	Database = "go-demo"
	MaxLifetime = 5
	MaxIdleConns = 10

[pgsqlSlave]
    Host="127.0.0.1:5432"
	Password = "123456"
	User = "root"
	Database = "go-demo"
	MaxLifetime = 5
	MaxIdleConns = 10

# redis 配置
[redis]
	Server = "127.0.0.1:6379"
    Password = ""
    RedisMaxIdleConn = 5
    RedisIdleTimeoutSec = 240
    SelectDb = 1

# KaProxy配置
[KaProxy]
    Scheme = "http"
    Host = "127.0.0.1"
    Port = 80
    Token = ""

# Grpc 配置

# 远程服务Host
[remoteHost]
    ServiceWebsocket = ""
