# 基本配置
Env = "pre" # 环境: pre 测试 beta 预发 release 生产
Mode="debug" #release debug test gin.mode
AppName = "go-demo"

# 端口
Port=3003

# pprof端口
PprofPort=9003

RpcPort=30030


# log
[log]
#debug info warn error
LogLevel = "debug"
LogFileStdout = "./go-demo.log"
LogFileErrorStdout = "./go-demo.error.log"
AppKey = "go-demo"

# KaProxy配置
[KaProxy]
Scheme = "http"
Host = "127.0.0.1"
Port = 80
Token = ""

# Grpc 配置

# 远程服务Host
[remoteHost]
ServiceWebsocket = ""
